// src/backgrounds/dark-lines.svelte
<script lang="ts">
  import { onMount, tick } from 'svelte';

  const hueRange = 70;

  let container: HTMLDivElement;
  let lines = [];
  let hue = 0;
  let frame;

  const nextHue = (currentHue: number) => {
    if (currentHue === 360) {
      return 0;
    }

    return currentHue + 1;
  };
  const buildLines = (height: number) => {
    const count = Math.round(height * 0.05);
    const hueStep = hueRange / count;

    hue = nextHue(hue);

    lines = [...new Array(count)].map((v, i) => ({
      index: i,
      y: (100 / count) * i,
      color: `hsl(${hue + hueStep * i}deg, 100%, 50%)`,
      delay: (100 / count) * i * i,
    }));
  };

  const render = () => {
    const height = container.offsetHeight;

    clearInterval(frame);
    frame = setInterval(() => {
      buildLines(height);
    }, 1000 / 60);
  };

  const deferRender = () => {
    setTimeout(() => {
      requestAnimationFrame(render);
    }, 1);
  };

  onMount(deferRender);
</script>

<style>
  @keyframes appear {
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }

  div {
    position: absolute;
    pointer-events: none;
    display: flex;
    width: 100%;
    height: 100%;
  }

  svg {
    display: block;
    flex: 1;
  }

  svg line {
    stroke-width: 1px;
    animation-name: appear;
    animation-duration: 500ms;
    animation-timing-function: ease;
    animation-direction: normal;
    animation-fill-mode: both;
    opacity: 0;
    transform: translateY(80px);
  }
</style>

<svelte:window on:resize={render} />

<div bind:this={container}>
  <svg>
    {#each lines as line}
      <line
        x1="0"
        y1="{line.y}%"
        x2="100%"
        y2="{line.y}%"
        stroke={line.color}
        style="animation-delay: {line.delay}ms;" />
    {/each}
  </svg>
</div>

// src/common/components/Background/DarkLines.tsx
import React, { useEffect, useMemo, useState } from 'react';
import { useWindowSize } from '../../../hooks';
import { addUnit } from '../../logic/geometry';
import styled, { keyframes } from 'styled-components';

const appear = keyframes`
  0% {
    opacity: 0;
    transform: translateY(100px);
  }
  100% {
    opacity: 1;
    transform: translateY(0);
  }
`;

const Line = styled.line`
  stroke-width: 1px;
  animation-name: ${appear};
  animation-duration: 500ms;
  animation-timing-function: ease;
  animation-direction: normal;
  animation-fill-mode: both;
  opacity: 0;
  transform: translateY(80px);
`;

const renderLines = (width: number, height: number, startHue: number) => {
  const hueRange = 100;
  const count = Math.round(height * 0.05);
  const hueStep = hueRange / count;

  return [...new Array(count)].map((v, i) => {
    const y = (100 / count) * i;
    const hue = startHue + hueStep * i;
    const color = `hsl(${hue}, 100%, 50%)`;
    const delay = addUnit((100 / count) * i * i, 'ms');

    return (
      <Line
        key={`${y}:${i}`}
        x1="0"
        y1={addUnit(y, '%')}
        x2="100%"
        y2={addUnit(y, '%')}
        stroke={color}
        style={{ animationDelay: delay }}
      />
    );
  });
};

const nextHue = (hue: number) => {
  if (hue === 360) {
    return 0;
  }

  return hue + 1;
};

const animateHue = (hue: number, setHue: (h: number) => void) => () => {
  const next = nextHue(hue);
  setHue(next);
  return requestAnimationFrame(animateHue(next, setHue));
};

const DarkLines: React.FC = () => {
  const { width, height } = useWindowSize();
  const [started, setStarted] = useState<boolean>(false);
  const [startHue, setHue] = useState<number>(70);
  const lines = useMemo(() => renderLines(width, height, startHue), [
    height,
    startHue,
    width,
  ]);

  useEffect(() => {
    if (!started) {
      setStarted(true);
      let frame = animateHue(startHue, setHue)();
      return () => {
        cancelAnimationFrame(frame);
        setStarted(false);
      };
    }
  }, [startHue, started]);

  return <svg>{lines}</svg>;
};

export default DarkLines;
