// src/App.svelte
<script lang="ts">
    import DarkLines from './backgrounds/dark-lines.svelte';
    import Yellow from './backgrounds/yellow.svelte';
    import Circles from './backgrounds/circles.svelte';
    import Waves from './backgrounds/waves.svelte';
    import Spirals from './backgrounds/spirals.svelte';
    import Content from "./content.svelte";

    const themes = ['dark-lines', 'yellow', 'circles', 'waves', 'spirals'];
    type ThemeName = typeof themes[number];

    const randomIndex = Math.floor(Math.random() * (themes.length - 1));
    let currentTheme: ThemeName = themes[randomIndex];

    const flipTheme = () => {
        const currIndex = themes.indexOf(currentTheme);
        const nextIndex = currIndex === themes.length - 1 ? 0 : currIndex + 1;
        currentTheme = themes[nextIndex];
    }
</script>

<main class="{currentTheme}">
    <div class="background">
        {#if currentTheme === 'dark-lines'}
            <DarkLines />
        {:else if currentTheme === 'yellow'}
            <Yellow />
        {:else if currentTheme === 'circles'}
            <Circles />
        {:else if currentTheme === 'waves'}
            <Waves />
        {:else if currentTheme === 'spirals'}
            <Spirals />
        {/if}
    </div>

    <Content />

    <button on:click={flipTheme} title="Click me to change the theme">Click me :)</button>
</main>

<style>
    :root {
        --bg-color: hsl(0deg, 0%, 5%);
        --bg-color-transparent: hsl(0deg, 0%, 5%, 0);
        --fg-color: #ededed;
        --action-color: hsl(255deg, 100%, 50%);
    }

    main.dark-lines {
        --bg-color: hsl(0deg, 0%, 5%);
        --fg-color: #ededed;
        --action-color: hsl(255deg, 100%, 50%);
    }

    main.yellow {
        --bg-color: hsl(45 100% 50%);
        --fg-color: hsl(0, 0%, 15%);
        --action-color: hsl(255 100% 50%);
    }

    main.circles {
        --bg-color: hsl(330 100% 45%);
        --fg-color: hsl(0, 0%, 15%);
        --action-color: hsl(255 100% 50%);
    }

    main.waves {
        --bg-color: hsl(65 100% 55% / 1);
        --fg-color: hsl(220deg 100% 55%);
        --action-color: hsl(255 100% 50%);
    }

    main.spirals {
        --bg-color: hsl(0deg 100% 60%);
        --fg-color: hsl(0deg 50% 25%);
        --action-color: hsl(255 100% 50%);
    }

    main {
        display: flex;
        flex-direction: column;
        height: 100%;
        background: var(--bg-color);
        color: var(--fg-color);
    }

    .background {
        position: absolute;
        pointer-events: none;
        display: flex;
        width: 100%;
        height: 100%;
    }

    button {
        display: flex;
        align-self: flex-start;
        z-index: 10;
        margin: 0 0 4vw 6vw;
        -webkit-appearance: none;
        appearance: none;
        background-color: var(--fg-color);
        color: var(--bg-color);
        border: none;
        padding: .5em .75em;
        border-radius: 1em;
        line-height: 1;
        font-weight: 600;
    }
</style>

// src/App/App.tsx
import React, { Fragment } from 'react';
import { GlobalStyle } from './globalStyles';
import { useThemes } from '../context/ThemeContext';
import styled from 'styled-components';
import { Content } from '../common/components/Content';
import Background from '../common/components/Background';

const MainWrapper = styled.main`
  display: flex;
  flex-direction: column;
  height: 100%;
  background: var(--primary-color);
  color: var(--secondary-color);
  padding: 4vw 6vw;
`;

const ActionsWrapper = styled.div`
  flex: 0;
  position: relative;
  z-index: 10;
`;

const Button = styled.button`
  display: block;
  cursor: pointer;
  -webkit-appearance: none;
  appearance: none;
  background-color: var(--secondary-color);
  color: var(--primary-color);
  border: none;
  padding: 0.5em 0.75em;
  margin: 0;
  border-radius: 1em;
  line-height: 1;
  font-size: 1.2em;
  font-weight: 600;
  box-shadow: none;
  transform: scale(1);
  transition: all 150ms ease;

  &:hover,
  &:active {
    transform: scale(1.2);
    background-color: var(--primary-color);
    color: var(--secondary-color);
    box-shadow: 0 0 1em rgba(0, 0, 0, 0.3);
  }
`;

const App: React.FC = () => {
  const { theme, next } = useThemes();

  return (
    <Fragment>
      <GlobalStyle {...theme.config} />
      <MainWrapper>
        <Background theme={theme.name} />
        <Content />
        <ActionsWrapper>
          <Button onClick={() => next()} title="Click me to change the theme">
            Click me :)
          </Button>
        </ActionsWrapper>
      </MainWrapper>
    </Fragment>
  );
};

export default App;
